misc improvements

diff --git a/gittemplates_global/hooks/pre-commit b/gittemplates_global/hooks/pre-commit
--- a/gittemplates_global/hooks/pre-commit
+++ b/gittemplates_global/hooks/pre-commit
@@ -7,6 +7,16 @@
 #
 # To enable this hook, rename this file to "pre-commit".
 
+# Test whether file exists in current or parent directories
+find_in_cwd_or_parent() {
+  local slashes=${PWD//[^\/]/}; local directory=$PWD;
+  for (( n=${#slashes}; n>0; --n )); do
+    test -e $directory/$1 && echo "$directory/$1" && return 0
+    directory=$directory/..
+  done
+  return 1
+}
+
 if git rev-parse --verify HEAD >/dev/null 2>&1
 then
 	against=HEAD
@@ -44,6 +54,25 @@ If you know what you are doing you can disable this check using:
 EOF
 	exit 1
 fi
+
+# Determine if this build uses travis-ci and attempt to update the status
+# in a non-blocking way
+git stash -q --keep-index
+travis_yml="$(find_in_cwd_or_parent .travis.yml)"
+if ([ -f "${travis_yml}" ] && [ -f "/usr/local/bin/update_travis_ci_status" ]); then
+    echo "sleep 15 && /usr/local/bin/update_travis_ci_status" | at now >/dev/null 2>&1
+    echo "/usr/local/bin/update_travis_ci_status" | at now + 1 minute >/dev/null 2>&1
+    if which travis >/dev/null 2>&1; then
+	error_msg="$(travis lint ${travis_yml} | grep -i 'error')"
+	if [ "$error_msg" ]; then
+	    echo ".travis.yml failed travis lint, with the following error message:" >&2
+	    echo "$error_msg" >&2
+	    git stash pop -q
+	    exit 1
+	fi
+    fi
+fi
+git stash pop -q
 
 # If there are whitespace errors, print the offending file names and fail.
 exec git diff-index --check --cached $against --
